/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package picturehouse.views;

import java.sql.Date;
import java.text.SimpleDateFormat;
import org.javalite.activejdbc.Base;
import picturehouse.controllers.NewsletterController;
import picturehouse.models.Newsletter;

/**
 *
 * @author sevabaskin
 */
public class NewsletterPanel extends javax.swing.JPanel {
    private MainFrame parentFrame;

    /**
     * Creates new form NewsletterPanel
     */
    public NewsletterPanel() {
        initComponents();
    }
    public NewsletterPanel(MainFrame parentFrame) {
        initComponents();
        Base.open("com.mysql.jdbc.Driver", "jdbc:mysql://localhost/picturehouse_development", "testuser", "testuserpassword");
        // retrieve latest newsletter data
        NewsletterController controller = new NewsletterController();
        Newsletter nl = controller.loadNewsletter(Date.valueOf("2014-02-28"));
        String content = nl.getString("content");
        Date newsletterDate = Date.valueOf(nl.getString("date"));
        Base.close();
        // get newsletter's month name
        String newsletterMonth = new SimpleDateFormat("MMMM").format(newsletterDate);
        this.newsletterTitle.setText(newsletterMonth + " Newsletter");
        this.parentFrame = parentFrame;
        this.newsletterTextArea.setText(content);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newsletterTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newsletterTextArea = new javax.swing.JTextArea();
        goBackButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(550, 400));

        newsletterTitle.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        newsletterTitle.setText("Newsletter");

        newsletterTextArea.setEditable(false);
        newsletterTextArea.setColumns(20);
        newsletterTextArea.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        newsletterTextArea.setLineWrap(true);
        newsletterTextArea.setRows(5);
        newsletterTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newsletterTextArea.setDisabledTextColor(java.awt.SystemColor.textText);
        newsletterTextArea.setEnabled(false);
        jScrollPane1.setViewportView(newsletterTextArea);

        goBackButton.setText("Return to Main Screen");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(goBackButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newsletterTitle)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newsletterTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        this.parentFrame.showCard("homePageCard");
    }//GEN-LAST:event_goBackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goBackButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea newsletterTextArea;
    private javax.swing.JLabel newsletterTitle;
    // End of variables declaration//GEN-END:variables
}
