/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package picturehouse.views;

/**
 *
 * @author sevabaskin
 */
public class NewTestPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewTestPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        seatPlanPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        a1Button = new javax.swing.JToggleButton();
        a2Button = new javax.swing.JToggleButton();
        a2Button1 = new javax.swing.JToggleButton();
        a2Button2 = new javax.swing.JToggleButton();
        a2Button3 = new javax.swing.JToggleButton();
        a2Button4 = new javax.swing.JToggleButton();
        a2Button5 = new javax.swing.JToggleButton();
        a2Button6 = new javax.swing.JToggleButton();
        a2Button7 = new javax.swing.JToggleButton();
        a2Button8 = new javax.swing.JToggleButton();
        a1Button1 = new javax.swing.JToggleButton();
        a2Button9 = new javax.swing.JToggleButton();
        a2Button10 = new javax.swing.JToggleButton();
        a2Button11 = new javax.swing.JToggleButton();
        a2Button12 = new javax.swing.JToggleButton();
        a2Button13 = new javax.swing.JToggleButton();
        a2Button14 = new javax.swing.JToggleButton();
        a2Button15 = new javax.swing.JToggleButton();
        a2Button16 = new javax.swing.JToggleButton();
        a2Button17 = new javax.swing.JToggleButton();
        a1Button2 = new javax.swing.JToggleButton();
        a2Button18 = new javax.swing.JToggleButton();
        a2Button19 = new javax.swing.JToggleButton();
        a2Button20 = new javax.swing.JToggleButton();
        a2Button21 = new javax.swing.JToggleButton();
        a2Button22 = new javax.swing.JToggleButton();
        a2Button23 = new javax.swing.JToggleButton();
        a2Button24 = new javax.swing.JToggleButton();
        a2Button25 = new javax.swing.JToggleButton();
        a2Button26 = new javax.swing.JToggleButton();
        a1Button3 = new javax.swing.JToggleButton();
        a2Button27 = new javax.swing.JToggleButton();
        a2Button28 = new javax.swing.JToggleButton();
        a2Button29 = new javax.swing.JToggleButton();
        a2Button30 = new javax.swing.JToggleButton();
        a2Button31 = new javax.swing.JToggleButton();
        a2Button32 = new javax.swing.JToggleButton();
        a2Button33 = new javax.swing.JToggleButton();
        a2Button34 = new javax.swing.JToggleButton();
        a2Button35 = new javax.swing.JToggleButton();
        a1Button4 = new javax.swing.JToggleButton();
        a2Button36 = new javax.swing.JToggleButton();
        a2Button37 = new javax.swing.JToggleButton();
        a2Button38 = new javax.swing.JToggleButton();
        a2Button39 = new javax.swing.JToggleButton();
        a2Button40 = new javax.swing.JToggleButton();
        a2Button41 = new javax.swing.JToggleButton();
        a2Button42 = new javax.swing.JToggleButton();
        a2Button43 = new javax.swing.JToggleButton();
        a2Button44 = new javax.swing.JToggleButton();
        a1Button5 = new javax.swing.JToggleButton();
        a2Button45 = new javax.swing.JToggleButton();
        a2Button46 = new javax.swing.JToggleButton();
        a2Button47 = new javax.swing.JToggleButton();
        a2Button48 = new javax.swing.JToggleButton();
        a2Button49 = new javax.swing.JToggleButton();
        a2Button50 = new javax.swing.JToggleButton();
        a2Button51 = new javax.swing.JToggleButton();
        a2Button52 = new javax.swing.JToggleButton();
        a2Button53 = new javax.swing.JToggleButton();
        a1Button6 = new javax.swing.JToggleButton();
        a2Button54 = new javax.swing.JToggleButton();
        a2Button55 = new javax.swing.JToggleButton();
        a2Button56 = new javax.swing.JToggleButton();
        a2Button57 = new javax.swing.JToggleButton();
        a2Button58 = new javax.swing.JToggleButton();
        a2Button59 = new javax.swing.JToggleButton();
        a2Button60 = new javax.swing.JToggleButton();
        a2Button61 = new javax.swing.JToggleButton();
        a2Button62 = new javax.swing.JToggleButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Choose a screening");

        jList1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Tuesday 7pm", "Wednesday 6pm", "Thursday 3pm", "Friday 4pm", "Saturday 5pm" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setSelectedIndex(0);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton1.setText("< Movie Browsing");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Tickets Selected:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("3");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("£12");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("Ticket Price:");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("£3");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("Total cost:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Choose your seats");

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton2.setText("Book Now");

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Screen");
        jLabel3.setOpaque(true);

        a1Button.setText("A1");
        a1Button.setFocusPainted(false);
        a1Button.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button.setText("A2");
        a2Button.setFocusPainted(false);
        a2Button.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button1.setText("A3");
        a2Button1.setFocusPainted(false);
        a2Button1.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button2.setText("A4");
        a2Button2.setFocusPainted(false);
        a2Button2.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button3.setText("A5");
        a2Button3.setFocusPainted(false);
        a2Button3.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button4.setText("A6");
        a2Button4.setFocusPainted(false);
        a2Button4.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button5.setText("A7");
        a2Button5.setFocusPainted(false);
        a2Button5.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button6.setText("A8");
        a2Button6.setFocusPainted(false);
        a2Button6.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button7.setText("A9");
        a2Button7.setFocusPainted(false);
        a2Button7.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button8.setText("A10");
        a2Button8.setFocusPainted(false);
        a2Button8.setMaximumSize(new java.awt.Dimension(75, 75));

        a1Button1.setText("B1");
        a1Button1.setFocusPainted(false);
        a1Button1.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button9.setText("B2");
        a2Button9.setFocusPainted(false);
        a2Button9.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button10.setText("B3");
        a2Button10.setFocusPainted(false);
        a2Button10.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button11.setText("A4");
        a2Button11.setFocusPainted(false);
        a2Button11.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button12.setText("A5");
        a2Button12.setFocusPainted(false);
        a2Button12.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button13.setText("A6");
        a2Button13.setFocusPainted(false);
        a2Button13.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button14.setText("A7");
        a2Button14.setFocusPainted(false);
        a2Button14.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button15.setText("A8");
        a2Button15.setFocusPainted(false);
        a2Button15.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button16.setText("A9");
        a2Button16.setFocusPainted(false);
        a2Button16.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button17.setText("A10");
        a2Button17.setFocusPainted(false);
        a2Button17.setMaximumSize(new java.awt.Dimension(75, 75));

        a1Button2.setText("A1");
        a1Button2.setFocusPainted(false);
        a1Button2.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button18.setText("A2");
        a2Button18.setFocusPainted(false);
        a2Button18.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button19.setText("A3");
        a2Button19.setFocusPainted(false);
        a2Button19.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button20.setText("A4");
        a2Button20.setFocusPainted(false);
        a2Button20.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button21.setText("A5");
        a2Button21.setFocusPainted(false);
        a2Button21.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button22.setText("A6");
        a2Button22.setFocusPainted(false);
        a2Button22.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button23.setText("A7");
        a2Button23.setFocusPainted(false);
        a2Button23.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button24.setText("A8");
        a2Button24.setFocusPainted(false);
        a2Button24.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button25.setText("A9");
        a2Button25.setFocusPainted(false);
        a2Button25.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button26.setText("A10");
        a2Button26.setFocusPainted(false);
        a2Button26.setMaximumSize(new java.awt.Dimension(75, 75));

        a1Button3.setText("A1");
        a1Button3.setFocusPainted(false);
        a1Button3.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button27.setText("A2");
        a2Button27.setFocusPainted(false);
        a2Button27.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button28.setText("A3");
        a2Button28.setFocusPainted(false);
        a2Button28.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button29.setText("A4");
        a2Button29.setFocusPainted(false);
        a2Button29.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button30.setText("A5");
        a2Button30.setFocusPainted(false);
        a2Button30.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button31.setText("A6");
        a2Button31.setFocusPainted(false);
        a2Button31.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button32.setText("A7");
        a2Button32.setFocusPainted(false);
        a2Button32.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button33.setText("A8");
        a2Button33.setFocusPainted(false);
        a2Button33.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button34.setText("A9");
        a2Button34.setFocusPainted(false);
        a2Button34.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button35.setText("A10");
        a2Button35.setFocusPainted(false);
        a2Button35.setMaximumSize(new java.awt.Dimension(75, 75));

        a1Button4.setText("A1");
        a1Button4.setFocusPainted(false);
        a1Button4.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button36.setText("A2");
        a2Button36.setFocusPainted(false);
        a2Button36.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button37.setText("A3");
        a2Button37.setFocusPainted(false);
        a2Button37.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button38.setText("A4");
        a2Button38.setFocusPainted(false);
        a2Button38.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button39.setText("A5");
        a2Button39.setFocusPainted(false);
        a2Button39.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button40.setText("A6");
        a2Button40.setFocusPainted(false);
        a2Button40.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button41.setText("A7");
        a2Button41.setFocusPainted(false);
        a2Button41.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button42.setText("A8");
        a2Button42.setFocusPainted(false);
        a2Button42.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button43.setText("A9");
        a2Button43.setFocusPainted(false);
        a2Button43.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button44.setText("A10");
        a2Button44.setFocusPainted(false);
        a2Button44.setMaximumSize(new java.awt.Dimension(75, 75));

        a1Button5.setText("A1");
        a1Button5.setFocusPainted(false);
        a1Button5.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button45.setText("A2");
        a2Button45.setFocusPainted(false);
        a2Button45.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button46.setText("A3");
        a2Button46.setFocusPainted(false);
        a2Button46.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button47.setText("A4");
        a2Button47.setFocusPainted(false);
        a2Button47.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button48.setText("A5");
        a2Button48.setFocusPainted(false);
        a2Button48.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button49.setText("A6");
        a2Button49.setFocusPainted(false);
        a2Button49.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button50.setText("A7");
        a2Button50.setFocusPainted(false);
        a2Button50.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button51.setText("A8");
        a2Button51.setFocusPainted(false);
        a2Button51.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button52.setText("A9");
        a2Button52.setFocusPainted(false);
        a2Button52.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button53.setText("A10");
        a2Button53.setFocusPainted(false);
        a2Button53.setMaximumSize(new java.awt.Dimension(75, 75));

        a1Button6.setText("A1");
        a1Button6.setFocusPainted(false);
        a1Button6.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button54.setText("A2");
        a2Button54.setFocusPainted(false);
        a2Button54.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button55.setText("A3");
        a2Button55.setFocusPainted(false);
        a2Button55.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button56.setText("A4");
        a2Button56.setFocusPainted(false);
        a2Button56.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button57.setText("A5");
        a2Button57.setFocusPainted(false);
        a2Button57.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button58.setText("A6");
        a2Button58.setFocusPainted(false);
        a2Button58.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button59.setText("A7");
        a2Button59.setFocusPainted(false);
        a2Button59.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button60.setText("A8");
        a2Button60.setFocusPainted(false);
        a2Button60.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button61.setText("A9");
        a2Button61.setFocusPainted(false);
        a2Button61.setMaximumSize(new java.awt.Dimension(75, 75));

        a2Button62.setText("A10");
        a2Button62.setFocusPainted(false);
        a2Button62.setMaximumSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout seatPlanPanelLayout = new javax.swing.GroupLayout(seatPlanPanel);
        seatPlanPanel.setLayout(seatPlanPanelLayout);
        seatPlanPanelLayout.setHorizontalGroup(
            seatPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(seatPlanPanelLayout.createSequentialGroup()
                .addComponent(a1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(a2Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE))
            .addGroup(seatPlanPanelLayout.createSequentialGroup()
                .addComponent(a1Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(a2Button13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button17, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE))
            .addGroup(seatPlanPanelLayout.createSequentialGroup()
                .addComponent(a1Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button18, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button20, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button21, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(a2Button22, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button23, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button24, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button25, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button26, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE))
            .addGroup(seatPlanPanelLayout.createSequentialGroup()
                .addComponent(a1Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button27, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button28, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button29, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button30, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(a2Button31, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button32, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button33, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button34, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button35, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE))
            .addGroup(seatPlanPanelLayout.createSequentialGroup()
                .addComponent(a1Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button36, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button37, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button38, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button39, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(a2Button40, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button41, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button42, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button43, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button44, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE))
            .addGroup(seatPlanPanelLayout.createSequentialGroup()
                .addComponent(a1Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button45, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button46, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button47, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button48, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(a2Button49, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button50, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button51, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button52, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button53, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE))
            .addGroup(seatPlanPanelLayout.createSequentialGroup()
                .addComponent(a1Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button54, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button55, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button56, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button57, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(a2Button58, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button59, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button60, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button61, javax.swing.GroupLayout.PREFERRED_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a2Button62, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE))
        );
        seatPlanPanelLayout.setVerticalGroup(
            seatPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatPlanPanelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button17, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button18, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button20, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button21, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button22, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button23, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button24, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button25, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button26, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button27, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button28, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button29, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button30, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button31, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button32, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button33, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button34, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button35, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button36, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button37, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button38, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button39, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button40, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button41, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button42, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button43, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button44, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button45, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button46, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button47, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button48, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button49, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button50, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button51, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button52, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button53, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seatPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button54, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button55, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button56, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button57, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button58, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button59, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button60, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button61, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2Button62, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(seatPlanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seatPlanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void seatClicked(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton a1Button;
    private javax.swing.JToggleButton a1Button1;
    private javax.swing.JToggleButton a1Button2;
    private javax.swing.JToggleButton a1Button3;
    private javax.swing.JToggleButton a1Button4;
    private javax.swing.JToggleButton a1Button5;
    private javax.swing.JToggleButton a1Button6;
    private javax.swing.JToggleButton a2Button;
    private javax.swing.JToggleButton a2Button1;
    private javax.swing.JToggleButton a2Button10;
    private javax.swing.JToggleButton a2Button11;
    private javax.swing.JToggleButton a2Button12;
    private javax.swing.JToggleButton a2Button13;
    private javax.swing.JToggleButton a2Button14;
    private javax.swing.JToggleButton a2Button15;
    private javax.swing.JToggleButton a2Button16;
    private javax.swing.JToggleButton a2Button17;
    private javax.swing.JToggleButton a2Button18;
    private javax.swing.JToggleButton a2Button19;
    private javax.swing.JToggleButton a2Button2;
    private javax.swing.JToggleButton a2Button20;
    private javax.swing.JToggleButton a2Button21;
    private javax.swing.JToggleButton a2Button22;
    private javax.swing.JToggleButton a2Button23;
    private javax.swing.JToggleButton a2Button24;
    private javax.swing.JToggleButton a2Button25;
    private javax.swing.JToggleButton a2Button26;
    private javax.swing.JToggleButton a2Button27;
    private javax.swing.JToggleButton a2Button28;
    private javax.swing.JToggleButton a2Button29;
    private javax.swing.JToggleButton a2Button3;
    private javax.swing.JToggleButton a2Button30;
    private javax.swing.JToggleButton a2Button31;
    private javax.swing.JToggleButton a2Button32;
    private javax.swing.JToggleButton a2Button33;
    private javax.swing.JToggleButton a2Button34;
    private javax.swing.JToggleButton a2Button35;
    private javax.swing.JToggleButton a2Button36;
    private javax.swing.JToggleButton a2Button37;
    private javax.swing.JToggleButton a2Button38;
    private javax.swing.JToggleButton a2Button39;
    private javax.swing.JToggleButton a2Button4;
    private javax.swing.JToggleButton a2Button40;
    private javax.swing.JToggleButton a2Button41;
    private javax.swing.JToggleButton a2Button42;
    private javax.swing.JToggleButton a2Button43;
    private javax.swing.JToggleButton a2Button44;
    private javax.swing.JToggleButton a2Button45;
    private javax.swing.JToggleButton a2Button46;
    private javax.swing.JToggleButton a2Button47;
    private javax.swing.JToggleButton a2Button48;
    private javax.swing.JToggleButton a2Button49;
    private javax.swing.JToggleButton a2Button5;
    private javax.swing.JToggleButton a2Button50;
    private javax.swing.JToggleButton a2Button51;
    private javax.swing.JToggleButton a2Button52;
    private javax.swing.JToggleButton a2Button53;
    private javax.swing.JToggleButton a2Button54;
    private javax.swing.JToggleButton a2Button55;
    private javax.swing.JToggleButton a2Button56;
    private javax.swing.JToggleButton a2Button57;
    private javax.swing.JToggleButton a2Button58;
    private javax.swing.JToggleButton a2Button59;
    private javax.swing.JToggleButton a2Button6;
    private javax.swing.JToggleButton a2Button60;
    private javax.swing.JToggleButton a2Button61;
    private javax.swing.JToggleButton a2Button62;
    private javax.swing.JToggleButton a2Button7;
    private javax.swing.JToggleButton a2Button8;
    private javax.swing.JToggleButton a2Button9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel seatPlanPanel;
    // End of variables declaration                   
}
