/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package picturehouse.views;

import javax.swing.JOptionPane;
import org.javalite.activejdbc.Base;
import picturehouse.PictureHouse;
import picturehouse.controllers.MovieReviewController;
import picturehouse.models.Movie;
import picturehouse.views.MainFrame;

/**
 *
 * @author sevabaskin
 */
public class WriteReviewPanel extends javax.swing.JPanel {
    private PictureHouse app;
    private MainFrame parentFrame;
    private Movie targetMovie;
    /**
     * Creates new form WriteReviewPanel
     */
    public WriteReviewPanel() {
        initComponents();
    }
    public WriteReviewPanel(PictureHouse app, MainFrame parentFrame) {
        initComponents();
        this.app = app;
        this.parentFrame = parentFrame;
    }
    
    public void updateView() {
        this.targetMovie = this.parentFrame.getCurrentlySelectedMovie();
        this.cardTitle.setText("Leave your review for " + this.targetMovie.getString("title"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        movieReviewTextArea = new javax.swing.JTextArea();
        submitReviewButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();

        cardTitle.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N

        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 250));
        jScrollPane1.setSize(new java.awt.Dimension(400, 250));

        movieReviewTextArea.setColumns(20);
        movieReviewTextArea.setLineWrap(true);
        movieReviewTextArea.setRows(5);
        movieReviewTextArea.setPreferredSize(new java.awt.Dimension(380, 230));
        movieReviewTextArea.setSize(new java.awt.Dimension(380, 230));
        jScrollPane1.setViewportView(movieReviewTextArea);

        submitReviewButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        submitReviewButton.setText("Submit your review");
        submitReviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitReviewButtonActionPerformed(evt);
            }
        });

        goBackButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        goBackButton.setText("< Go Back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cardTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(goBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitReviewButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        this.parentFrame.showCard("browseMoviesCard");
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void submitReviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitReviewButtonActionPerformed
        if (movieReviewTextArea.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "A movie review cannot be blank! Please write something.", "Input Errors", JOptionPane.WARNING_MESSAGE);
        } else {
            Base.open("com.mysql.jdbc.Driver", "jdbc:mysql://localhost/picturehouse_development", "testuser", "testuserpassword");
            MovieReviewController controller = new MovieReviewController();
            controller.create(
                    this.app.getCurrentCustomer().getInteger("id"),
                    this.targetMovie.getInteger("id"),
                    movieReviewTextArea.getText());
//            this.parentFrame.updateCard("homePageCard");
            Base.close();
            this.parentFrame.showCard("browseMoviesCard");
            movieReviewTextArea.setText("");
        }
    }//GEN-LAST:event_submitReviewButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardTitle;
    private javax.swing.JButton goBackButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea movieReviewTextArea;
    private javax.swing.JButton submitReviewButton;
    // End of variables declaration//GEN-END:variables
}
